#Auto generated by Edalize

TARGET   := test_vivado_yosys_0

all: $(TARGET).edif

DEPENDENCIES := yosys.tcl
%.blif: ${DEPENDENCIES}
	yosys -l yosys.log -p "tcl yosys.tcl"
%.json: ${DEPENDENCIES}
	yosys -l yosys.log -p "tcl yosys.tcl"
%.edif: ${DEPENDENCIES}
	yosys -l yosys.log -p "tcl yosys.tcl"

clean:
	rm -f $(TARGET).blif $(TARGET).json $(TARGET).edif
